### ISSUE TITLE
Keep alive

### ISSUE THREAD

**Issue by psykzz** [liamcottle/rustplus.js#35]
There are a number of times when the socket seems to die, or just stop responding for me.
Could we implement some keepalive?

For example if they have ping / pong, or perhaps every minute to do a `getServerInfo` request (if no other request has been done).

Obviously i can do this myself, but would love it to be part of the framework.

**Comment by liamcottle** [comment]
There's no ping/pong message implemented in the protocol as the official app doesn't need it. They already do a `getInfo` request every few seconds.

I think for now, since the rust+ server enforces rate limits, I don't want the library to consume requests that are just going to be discarded. This would also mean responses would be triggered for message listeners, and users might be confused as to why they are receiving messages for something they never requested.

Related Issue: https://github.com/liamcottle/rustplus.js/issues/16
