### ISSUE TITLE
getCameraFrames will break nearby player's point of view

### ISSUE THREAD

**Issue by KuroNoDev** [liamcottle/rustplus.js#5]
I noticed that players near enough to a CCTV that has been requested for a frame at least once will break those players' POVs. Reconnecting to the server (but still staying within the affected area of the CCTV) will temporarily fix it but will only last for a few seconds.

![CCTV BUG](https://user-images.githubusercontent.com/11919797/89681469-fa0bf780-d92f-11ea-9a1d-dd895715ba44.png)

Do you have an idea on why this happens?

**Comment by liamcottle** [comment]
Can't say I've ever seen this happen, however the CCTV stuff was still in early development at the time and wasn't actually available in the mobile Rust+ app. Pretty sure CCTV is still disabled in the app, but I haven't checked this for a long time.

**Comment by D3XX3R** [comment]
This issue still exists. I didn't notice it till I looked down. Happens when you request a lot of images.

**Comment by normie94** [comment]
could you share the snippet you used to get a camera frame?

**Comment by D3XX3R** [comment]
I used this here
https://github.com/liamcottle/rustplus.js/issues/2#issuecomment-645316862

**Comment by liamcottle** [comment]
CCTV still isn't in the Rust+ app as far as I can tell, and you have to go out of your way to enable it on the server. I'm assuming the devs are aware of the bugs, hence it's not available for us to play with in the official app.

I'm going to close this issue since it's not something we can fix in this library :)
