### ISSUE TITLE
How did you figure out how to build the correct request to send to the server?

### ISSUE THREAD

**Issue by sb-89** [liamcottle/rustplus.js#72]
I guess from debugging outgoing requests on the android app?

**Comment by liamcottle** [comment]
- Transferred the Rust+ APK from my phone to my PC.
- Decompiled the APK with [apktool](https://apktool.org/)
- Found the javascript files since it's an [Expo](https://expo.dev/) app.
- Found the javascript file that contains the protobuf definitions.
- Also downloaded the Rust Server from steam, and decompiled the DLLs with [Jetbrains DotPeek](https://www.jetbrains.com/decompiler/).
